trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    - azure-pipelines.yml
    - .gitignore

pr:
  autoCancel: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - src/*
    - azure-pipelines.yml
    - .gitignore

jobs:
- job: blazor_clipboard
  displayName: Blazor Clipboard
  timeoutInMinutes: 15
  workspace:
    clean: all
  strategy:
      maxParallel: 1
  pool:
      vmImage: ubuntu-16.04
  variables:
    buildConfiguration: 'Release'
    restoreBuildProjects: '**/*.csproj'
    testProjects: '**/*Test.csproj'
    packProject: '**/BlazorClipboard.csproj'
    dotnetSDK: 3.0.100-preview6-012264
  steps:
  - checkout: self
    clean: true
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk'
    inputs:
      version: $(dotnetSDK)
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(restoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(restoreBuildProjects)
      arguments: --configuration $(buildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(testProjects)
      arguments: --configuration $(buildConfiguration) --no-build
  - task: DotNetCoreCLI@2
    displayName: pack
    inputs:
      command: pack
      projects: $(publishProject)
      arguments: --configuration $(buildConfiguration) --project $(packProject) --no-build